"""DAIMON Canon Mapping — generated 2026-04-23.
Source of truth for the mythology pivot. Consumed by tools/canon_rewrite/apply.py
to patch daimon/catalog/v1_alpha/*.json.

Each entry: card_id -> dict with:
  - name (str): mythological display name
  - species (str): species stem (lowercase, underscore)
  - canon (str): OLYMPIAN | AESIR | NETJER | KAMI | TEOTL | APOCRYPHA
  - flavor (str): one-line lore in the Canon's voice (<= 110 chars)
  - moves (dict[str, str]): old_move_name -> new_move_name (must cover ALL existing moves)

Audit overrides (docs/canon_audit.md §2 + §3-SWAPs + §5) and Santiago directives
2026-04-23 (Phoenix V2 reservations: ashen_phoenix=Prometheus-Unbound,
solar_phoenix=Helios, concord_phoenix=The First Ancestor) are baked in.
"""

MAPPING: dict[str, dict] = {
    # ===================== OLYMPIAN =====================
    "magma_tyrant": {
        "name": "Prometheus, Fire-Thief",
        "species": "prometheus",
        "canon": "OLYMPIAN",
        "flavor": "He stole flame from the sky; the punishment is that flame still answers him.",
        "moves": {"Sovereign Ember": "Stolen Fire"},
    },
    "pyrotyrant": {
        "name": "Typhon",
        "species": "typhon",
        "canon": "OLYMPIAN",
        "flavor": "Hundred-throated, mountain-shouldered, the last child of Gaia to dare the sky.",
        "moves": {
            "Ascend the Throne": "Climb to Olympos",
            "Rule by Fire": "Reign in Brimstone",
            "Funeral of the World": "Pyre for the Gods",
        },
    },
    "molten_drake": {
        "name": "Lernean Pyrohydra",
        "species": "pyrohydra",
        "canon": "OLYMPIAN",
        "flavor": "Cousin to Lerna's serpent — sever a head and a candle answers in its place.",
        "moves": {"Sunsplit Breath": "Hydra's Breath"},
    },
    "ashen_phoenix": {
        "name": "Prometheus-Unbound",
        "species": "prometheus_unbound",
        "canon": "OLYMPIAN",
        "flavor": "The chains broke at last; the eagle still circles, but the gift goes to others now.",
        "moves": {
            "Ember Dirge": "Liver's Lament",
            "Hearth Anthem": "Gift of the Unbound",
        },
    },
    "inferno_lynx": {
        "name": "Chimaera",
        "species": "chimaera",
        "canon": "OLYMPIAN",
        "flavor": "Lion-fronted, goat-spined, serpent-tailed — and burning at every seam.",
        "moves": {
            "Quickflame": "Triform Sprint",
            "Searing Pounce": "Three-Mouthed Pounce",
        },
    },
    "pyroshrike": {
        "name": "Chalkotaur Calf",
        "species": "chalkotaur",
        "canon": "OLYMPIAN",
        "flavor": "Hephaestus's bronze bulls were calves once — and even then they breathed forge-fire.",
        "moves": {"Burning Lance": "Bronze-Horn Lance"},
    },
    "tide_empress": {
        "name": "Amphitrite, Sea-Queen",
        "species": "amphitrite",
        "canon": "OLYMPIAN",
        "flavor": "Consort of Poseidon, sovereign of the salt-throne; the wave bows where her foot falls.",
        "moves": {"Coronal Trickle": "Diadem of the Tide"},
    },
    "leviathan_prime": {
        "name": "Keto Primeval",
        "species": "keto",
        "canon": "OLYMPIAN",
        "flavor": "Mother of monsters in the dark below, before the gods drew lots for the sea.",
        "moves": {
            "Aegis of the Deep": "Mantle of the Deep",
            "World-Crushing Maw": "Maw of the Primeval",
            "Tide Returns": "The Sea Reclaims",
        },
    },
    "maelstrom_serpent": {
        "name": "Charybdis",
        "species": "charybdis",
        "canon": "OLYMPIAN",
        "flavor": "Thrice-daily she gulps the strait; thrice-daily the keels splinter in her throat.",
        "moves": {
            "Hull-Crack": "Hull-Splitter",
            "Spiral Lash": "Whirlpool Lash",
        },
    },
    "glacier_kraken": {
        "name": "Kraken of Aegaeon",
        "species": "kraken",
        "canon": "OLYMPIAN",
        "flavor": "Frost-bound cousin of the deep-kraken; even its silence cracks the hull.",
        "moves": {"Iceflow Bulwark": "Bulwark of Aegaeon"},
    },
    "coral_augur": {
        "name": "Scylla, Reef-Witch",
        "species": "scylla",
        "canon": "OLYMPIAN",
        "flavor": "Twelve-voiced oracle of the strait — she names the drowned before the wave is done.",
        "moves": {
            "Pristine Tide": "Pristine Reef-Song",
            "Tidewarded": "Twelvefold Ward",
        },
    },
    "riptide_wyrm": {
        "name": "Thetis, Silver-Footed",
        "species": "thetis",
        "canon": "OLYMPIAN",
        "flavor": "Silver-footed nymph who shielded a hero in the river; her hand still warms the wounded.",
        "moves": {
            "Tidal Shroud": "Silver-Footed Shroud",
            "Salve Surge": "Mother's Salve",
        },
    },
    "coral_priest": {
        "name": "Nereid Priestess",
        "species": "nereid",
        "canon": "OLYMPIAN",
        "flavor": "Daughter of Nereus, she sings the salt into wounds and the wounds into salt.",
        "moves": {},
    },
    "tide_chanter": {
        "name": "Siren of Anthemoessa",
        "species": "siren",
        "canon": "OLYMPIAN",
        "flavor": "On the meadow-isle she sings; the rowers turn, and the rowers do not return.",
        "moves": {},
    },
    "sea_warden": {
        "name": "Karkinos, Deep-Crab",
        "species": "karkinos",
        "canon": "OLYMPIAN",
        "flavor": "The crab Hera sent against Heracles — crushed underfoot, set in stars, still hungry.",
        "moves": {},
    },
    "tidewatcher": {
        "name": "Glaukos",
        "species": "glaukos",
        "canon": "OLYMPIAN",
        "flavor": "A fisherman who tasted the green herb; his skin became scale and his eye became sea.",
        "moves": {},
    },
    "frostfin": {
        "name": "Telchine of the Tide",
        "species": "telchine",
        "canon": "OLYMPIAN",
        "flavor": "Sea-smiths whose hammered curses dulled the bronze of better men.",
        "moves": {"Numbing Strike": "Smith-Curse Strike"},
    },
    "krakenling": {
        "name": "Krakenling",
        "species": "krakenling",
        "canon": "OLYMPIAN",
        "flavor": "Born in the trench, learning already the weight of the Aegean above.",
        "moves": {},
    },
    "worldroot_sentinel": {
        "name": "Gaia, Worldmother",
        "species": "gaia",
        "canon": "OLYMPIAN",
        "flavor": "The earth herself, broad-breasted, who gave the gods their thrones and outlasts them.",
        "moves": {"Mantle of Bark": "Mantle of the World"},
    },
    "bulwark_patriarch": {
        "name": "Kronos, Titan-Father",
        "species": "kronos",
        "canon": "OLYMPIAN",
        "flavor": "Deposed lord of the golden age; the scythe rusts but the patience does not.",
        "moves": {
            "Patient Verdure": "Patient Aeons",
            "Set the Roots": "Set the Old Order",
        },
    },
    "mossbear": {
        "name": "Kodama Elder",
        "species": "kodama_elder",
        "canon": "KAMI",
        "flavor": "Bark-skin, slow heartbeat — the grove answers when its eldest is struck.",
        "moves": {},
    },
    "petalwing": {
        "name": "Meliai",
        "species": "meliai",
        "canon": "OLYMPIAN",
        "flavor": "Ash-tree nymphs born of Ouranos's blood; their petals close every wound but one.",
        "moves": {},
    },
    "bramblegoat": {
        "name": "Aegipan",
        "species": "aegipan",
        "canon": "OLYMPIAN",
        "flavor": "Goat-horned forest-guardian; the hedge thickens where his hoof has passed.",
        "moves": {"Hedgewall": "Aegipan's Hedge"},
    },
    "storm_celestial": {
        "name": "Zeus, Sky-Lord",
        "species": "zeus",
        "canon": "OLYMPIAN",
        "flavor": "Cloud-gatherer, thunder-thrower; he reigns and the lesser sky obeys.",
        "moves": {
            "Heaven's Tempo": "Olympian Tempo",
            "Skyfall Volley": "Thunderbolt Volley",
            "Mourner's Charge": "Aegis-Charge",
        },
    },
    "tempest_eagle": {
        "name": "Aetos Dios",
        "species": "aetos",
        "canon": "OLYMPIAN",
        "flavor": "Zeus's golden eagle — bearer of bolts, herald of the throne above the throne.",
        "moves": {"Skyfall Talons": "Bolt-Bearing Talons"},
    },
    "plasma_djinn": {
        "name": "Astrape",
        "species": "astrape",
        "canon": "OLYMPIAN",
        "flavor": "The lightning made woman; she walks beside Zeus and burns where she is asked.",
        "moves": {
            "Quicken the Court": "Quicken Olympos",
            "Wishlash": "Bright-Lash",
        },
    },
    "glimmerowl": {
        "name": "Glaukos-Owl of Athena",
        "species": "owl_of_athena",
        "canon": "OLYMPIAN",
        "flavor": "Grey-eyed bird of the grey-eyed goddess; what she sees by lamp, it sees by storm.",
        "moves": {
            "Static Swoop": "Owl-Swoop of Pallas",
            "Forewarning": "Grey-Eyed Foresight",
        },
    },
    "arc_serpent": {
        "name": "Python of Delphi",
        "species": "python_delphi",
        "canon": "OLYMPIAN",
        "flavor": "The first oracle was a serpent at the navel-stone; the lightning is its modern tongue.",
        "moves": {
            "Coil & Conduct": "Coil at the Omphalos",
            "Arc Lash": "Oracle's Lash",
        },
    },
    "prism_strider": {
        "name": "Iris, Rainbow-Courier",
        "species": "iris",
        "canon": "OLYMPIAN",
        "flavor": "Bow of the gods bent across the sky; she carries the message between the thrones.",
        "moves": {},
    },
    "prismbolt": {
        "name": "Iris-Mote",
        "species": "iris_mote",
        "canon": "OLYMPIAN",
        "flavor": "A fleck of the rainbow-courier's bow; the small message before the great one.",
        "moves": {},
    },
    "voidking_morr": {
        "name": "Hades, Unseen-King",
        "species": "hades",
        "canon": "OLYMPIAN",
        "flavor": "Lord of the rich land below; his crown is forged of asphodel, his court of silence.",
        "moves": {
            "Sovereign Pall": "Pall of the Unseen",
            "Feast on Loss": "Toll for the Crossing",
            "Throne of Silence": "Throne Beneath the Stone",
        },
    },
    "echo_lich": {
        "name": "Erebus",
        "species": "erebus",
        "canon": "OLYMPIAN",
        "flavor": "Primordial dark beneath the earth, before there was a god to name him.",
        "moves": {
            "Lament Field": "Field of Erebus",
            "Feed on Loss": "Drink of the Forgotten",
            "Repetition Strike": "Echo from the Pit",
        },
    },
    "riftwraith": {
        "name": "Keres, Battle-Spirit",
        "species": "keres",
        "canon": "OLYMPIAN",
        "flavor": "Sister-fates of violent death; they crouch at the wound and drink while the man still names them.",
        "moves": {
            "Parting Tear": "Death-Spirits' Parting",
            "Fray": "Blood-Drinker's Fray",
        },
    },
    "nullhound": {
        "name": "Cerberus",
        "species": "cerberus",
        "canon": "OLYMPIAN",
        "flavor": "Three heads at the gate; one for the coming, one for the going, one that does not sleep.",
        "moves": {
            "Erase Edges": "Erase the Threshold",
            "Final Howl": "Triple-Throated Howl",
        },
    },
    "haunt_hare": {
        "name": "Lampas of Hekate",
        "species": "lampas",
        "canon": "OLYMPIAN",
        "flavor": "Torch-bearing hare of the witch-goddess; it crosses the crossroads and crosses again.",
        "moves": {
            "Phantom Step": "Crossroads-Step",
            "Dread Bite": "Witch-Hare's Bite",
        },
    },
    "crypt_wraith": {
        "name": "Thanatos, Reaper",
        "species": "thanatos",
        "canon": "OLYMPIAN",
        "flavor": "Soft-stepping brother of Sleep; even the strong yield to his cool hand at last.",
        "moves": {
            "Hush of Mourning": "Hush of Thanatos",
            "Parting Wail": "Soft-Stepping Wail",
        },
    },
    "mindroot": {
        "name": "Mandragora of Kokytos",
        "species": "mandragora_kokytos",
        "canon": "OLYMPIAN",
        "flavor": "Pulled from the wailing river — its scream poisons the ear and the year that hears it.",
        "moves": {
            "Tainted Spring": "Wailing-River Spring",
            "Closer's Whisper": "Mandrake-Scream",
        },
    },
    "whisperling": {
        "name": "Moros",
        "species": "moros",
        "canon": "OLYMPIAN",
        "flavor": "Doom-spirit; he murmurs the ending under every beginning.",
        "moves": {},
    },

    # ===================== AESIR =====================
    "flarelord": {
        "name": "Surtr",
        "species": "surtr",
        "canon": "AESIR",
        "flavor": "Fire comes from the south; Surtr the flame-wreathed bears a sword brighter than the sun.",
        "moves": {},
    },
    "flarefly": {
        "name": "Muspel-Spark",
        "species": "muspel_spark",
        "canon": "AESIR",
        "flavor": "Ember from the south-realm before the worlds; it remembers being older than ice.",
        "moves": {},
    },
    "brimling": {
        "name": "Eldjötunn Whelp",
        "species": "eldjotunn",
        "canon": "AESIR",
        "flavor": "Young of the fire-giants; small still, but the cradle scorches the rock.",
        "moves": {},
    },
    "tidewyrm": {
        "name": "Rán, Drowning-Queen",
        "species": "ran",
        "canon": "AESIR",
        "flavor": "She casts her net in the cold green water and gathers the drowned to her hall.",
        "moves": {
            "Surf Strike": "Net of Rán",
            "Healing Tide": "Drowning-Hall Welcome",
        },
    },
    "tide_imp": {
        "name": "Rán-Maiden",
        "species": "ran_maiden",
        "canon": "AESIR",
        "flavor": "Daughter of the net-queen; she counts the drowned by their belt-buckles.",
        "moves": {},
    },
    "mistray": {
        "name": "Havmand's Fin",
        "species": "havmand",
        "canon": "AESIR",
        "flavor": "Merman of the cold north water; the fin breaks the surface, the rest is rumor.",
        "moves": {},
    },
    "spring_otter": {
        "name": "Otr of Andvari",
        "species": "otr",
        "canon": "AESIR",
        "flavor": "Shape-shifter slain by Loki's stone; his pelt is the curse that doomed the Niflungs.",
        "moves": {},
    },
    "dewfin": {
        "name": "Brunnmigi",
        "species": "brunnmigi",
        "canon": "AESIR",
        "flavor": "Spring-fouler of the homestead; the well goes sour where his shadow has crossed.",
        "moves": {},
    },
    "abysseel": {
        "name": "Fossegrim",
        "species": "fossegrim",
        "canon": "AESIR",
        "flavor": "Waterfall-spirit who plays the fiddle; the salmon learn the tune and the boys do not return.",
        "moves": {"Pressure Shell": "Fossegrim's Coil"},
    },
    "saltsprite": {
        "name": "Meermin",
        "species": "meermin",
        "canon": "AESIR",
        "flavor": "Salt-spray sprite of the longship's wake; small, but the cold remembers her.",
        "moves": {},
    },
    "worldroot_colossus": {
        "name": "Yggdrasil-Root",
        "species": "yggdrasil_root",
        "canon": "AESIR",
        "flavor": "A root of the world-ash given walking shape; it carries the weight that holds the nine.",
        "moves": {
            "Anchor of Eras": "Anchor of the World-Ash",
            "Verdant Pulse": "Yggdrasil-Pulse",
            "Last Bloom": "Last Bloom of the Nine",
        },
    },
    "moss_titan": {
        "name": "Jötunn of Jotunheim",
        "species": "jotunn",
        "canon": "AESIR",
        "flavor": "Stone-and-rime giant of the eastern realm; the mountain walks and the snow follows.",
        "moves": {
            "Bedrock Stance": "Bedrock of Jotunheim",
            "Patient Bark": "Patience of the Cold",
        },
    },
    "forest_warden": {
        "name": "Huldra, Forest-Hidden",
        "species": "huldra",
        "canon": "AESIR",
        "flavor": "Beautiful from the front, hollow at the back — and the woodsman never wakes the same.",
        "moves": {
            "Grove Aegis": "Hidden-Folk Aegis",
            "Sapwell Surge": "Sapwell of the Hollow",
        },
    },
    "iron_boar": {
        "name": "Gullinbursti",
        "species": "gullinbursti",
        "canon": "AESIR",
        "flavor": "Freyr's golden-bristled boar; the bristles light the night-road, the tusks open the morning.",
        "moves": {"Plated Charge": "Golden-Bristled Charge"},
    },
    "ironseed": {
        "name": "Acorn of Yggdrasil",
        "species": "yggdrasil_seed",
        "canon": "AESIR",
        "flavor": "A seed-shard of the world-ash; from such a thing the nine realms once grew.",
        "moves": {},
    },
    "barkpup": {
        "name": "Skogsrå Pup",
        "species": "skogsra",
        "canon": "AESIR",
        "flavor": "Forest-warden's young; the bark grows over the wound while the pup still nurses.",
        "moves": {},
    },
    "barkguard": {
        "name": "Skogsrå Warden",
        "species": "skogsra",
        "canon": "AESIR",
        "flavor": "Grown into the grove; the trees bend where she walks, and the bear gives way.",
        "moves": {},
    },
    "bramble_warden": {
        "name": "Thyrsus-Bearer",
        "species": "thyrsus_bearer",
        "canon": "AESIR",
        "flavor": "Thorn-staffed druid of the cold groves; the briar answers to the staff's tap.",
        "moves": {},
    },
    "brambleling": {
        "name": "Nisse of the Hedge",
        "species": "hedge_nisse",
        "canon": "AESIR",
        "flavor": "Hedge-house spirit; leave the bowl of porridge or the cattle will not drink at dawn.",
        "moves": {},
    },
    "forest_cub": {
        "name": "Bjarn Cub",
        "species": "bjarn",
        "canon": "AESIR",
        "flavor": "Bear-cub of the northern wood; soon enough the stride will match the father's.",
        "moves": {},
    },
    "forest_keeper": {
        "name": "Skogsrå Elder",
        "species": "skogsra_elder",
        "canon": "AESIR",
        "flavor": "Eldest of the hidden-folk; she tends the wound and she remembers the hand that gave it.",
        "moves": {},
    },
    "stone_titan": {
        "name": "Berg-Risi",
        "species": "bergrisi",
        "canon": "AESIR",
        "flavor": "Mountain-giant of the high crags; storms cling to him as moss to a stone.",
        "moves": {},
    },
    "sproutkin": {
        "name": "Vaetter Sapling",
        "species": "vaetter",
        "canon": "AESIR",
        "flavor": "Land-wight in seedling form; small, but the soil already knows its name.",
        "moves": {},
    },
    "tempest_apex": {
        "name": "Thor, Hammer-Bearer",
        "species": "thor",
        "canon": "AESIR",
        "flavor": "Red-bearded son of Odin; Mjölnir falls and the giants count themselves before the count.",
        "moves": {"Stormgrant Doctrine": "Mjölnir's Grant"},
    },
    "voltcat_apex": {
        "name": "Valravn",
        "species": "valravn",
        "canon": "AESIR",
        "flavor": "The raven who ate a king's heart and learned to walk as a wolf in the storm.",
        "moves": {
            "Plasma Lance": "Raven-Wolf's Lance",
            "Thunderstep": "Storm-Walking Stride",
        },
    },
    "voltsprite": {
        "name": "Ratatoskr",
        "species": "ratatoskr",
        "canon": "AESIR",
        "flavor": "Squirrel of the world-ash; he carries insults up the trunk and curses back down.",
        "moves": {"Quicken All": "Trunk-Running Tongue"},
    },
    "stormhare": {
        "name": "Vindhare",
        "species": "vindhare",
        "canon": "AESIR",
        "flavor": "Wind-hare of the northern moor; he runs ahead of the storm, and the storm follows.",
        "moves": {
            "Thunderdash": "Storm-Outracing Dash",
            "Rally Wind": "Wind-Hare's Cry",
        },
    },
    "spark_serpent": {
        "name": "Lyngorm",
        "species": "lyngorm",
        "canon": "AESIR",
        "flavor": "Heath-serpent of the Norse fen; lightning answers when his coil drinks the cloud.",
        "moves": {},
    },
    "thunderfly": {
        "name": "Skuld-Mote",
        "species": "skuld_mote",
        "canon": "AESIR",
        "flavor": "A spark off the youngest Norn's loom; what she has woven, the mote already knows.",
        "moves": {},
    },
    "crypt_seer": {
        "name": "Völva",
        "species": "volva",
        "canon": "AESIR",
        "flavor": "Seeress of the staff and the trance; she names the fallen before the funeral fire.",
        "moves": {},
    },
    "dirge_lich": {
        "name": "Draugr-King",
        "species": "draugr_king",
        "canon": "AESIR",
        "flavor": "Howe-king who refused the long sleep; the gold turned black, the king did not.",
        "moves": {},
    },
    "dread_kit": {
        "name": "Niflung Whelp",
        "species": "niflung_whelp",
        "canon": "AESIR",
        "flavor": "Mist-dead's young; born already cold, born already counting.",
        "moves": {},
    },
    "dread_warden": {
        "name": "Niflung Warden",
        "species": "niflung_warden",
        "canon": "AESIR",
        "flavor": "Elder of the misted dead; he tends the door between the rime and the road.",
        "moves": {},
    },
    "shadowpup": {
        "name": "Garm's Pup",
        "species": "garm_pup",
        "canon": "AESIR",
        "flavor": "Hellhound's young; the chain is short still, but the howl is already true.",
        "moves": {},
    },
    "shadow_warden": {
        "name": "Garm, Warden",
        "species": "garm",
        "canon": "AESIR",
        "flavor": "Hound at the gates of Hel; at Ragnarök his chain breaks, and Týr meets him at last.",
        "moves": {},
    },
    "cinderhound": {
        "name": "Garmr-Whelp",
        "species": "garmr_whelp",
        "canon": "AESIR",
        "flavor": "Fire-eyed pup of the hellhound-line; the ember in the eye outlasts the hand that strikes it.",
        "moves": {"Pain Bond": "Ember-Eyed Bond"},
    },
    "geodeling": {
        "name": "Bergrisi-Pup",
        "species": "bergrisi_pup",
        "canon": "AESIR",
        "flavor": "Mountain-giant's young; the boulder thickens around him as the pup remembers nothing.",
        "moves": {"Stone Pulse": "Mountain-Pulse"},
    },
    "voidling": {
        "name": "Draugr Dreg",
        "species": "draugr_dreg",
        "canon": "AESIR",
        "flavor": "Lesser of the howe-walkers; when the cold claims him at last, the lunge claims one of yours.",
        "moves": {},
    },

    # ===================== NETJER =====================
    "solar_phoenix": {
        "name": "Helios, Sun-Charioteer",
        "species": "helios",
        "canon": "OLYMPIAN",
        "flavor": "He drives the chariot from horizon to horizon; the dive at dawn, the bleeding light at dusk.",
        "moves": {
            "Sunbreak Dive": "Dawn-Chariot Dive",
            "Last Light": "Sunset Bequest",
        },
    },
    "ashpup": {
        "name": "Solar Cub",
        "species": "solar_cub",
        "canon": "NETJER",
        "flavor": "Young of the sun-disk; the light around him is yet small enough to cradle.",
        "moves": {},
    },
    "ash_strider": {
        "name": "Sunstrider of Ra",
        "species": "sunstrider",
        "canon": "NETJER",
        "flavor": "He walks where Ra has walked; the sand keeps the print, the print keeps the heat.",
        "moves": {},
    },
    "cinder_serpent": {
        "name": "Apep Hatchling",
        "species": "apep",
        "canon": "NETJER",
        "flavor": "Chaos-serpent's young; in the night-hours he learns the swallowing of the sun.",
        "moves": {},
    },
    "lava_skink": {
        "name": "Wadjet Skink",
        "species": "wadjet_skink",
        "canon": "NETJER",
        "flavor": "Cobra-shaped, sun-warmed; the uraeus rises from the brow when the king wakes.",
        "moves": {},
    },
    "magmite": {
        "name": "Sekhet-Spark",
        "species": "sekhet_spark",
        "canon": "NETJER",
        "flavor": "Ember-fragment from the sun-field of the blessed; the spark that walks of itself.",
        "moves": {"Spitfire": "Sun-Field Spit"},
    },
    "abyss_minnow": {
        "name": "Sobek-Hatchling",
        "species": "sobek_hatchling",
        "canon": "NETJER",
        "flavor": "Crocodile-god's young; even at this size, the tooth knows the meat.",
        "moves": {},
    },
    "abyssbreaker": {
        "name": "Sobek Adept",
        "species": "sobek_adept",
        "canon": "NETJER",
        "flavor": "Initiate of the crocodile-temple; the river closes its mouth around him in approval.",
        "moves": {},
    },
    "coralwhelp": {
        "name": "Nile Whelp",
        "species": "nile_whelp",
        "canon": "NETJER",
        "flavor": "Hatchling of the great river; the reeds bend to hide him, the heron does not.",
        "moves": {},
    },
    "tidefry": {
        "name": "Ra-Barque Pilotfish",
        "species": "ra_pilot",
        "canon": "NETJER",
        "flavor": "Escort-fish to the solar boat; he swims before the dawn and never tires.",
        "moves": {},
    },
    "bulwarthog": {
        "name": "Khepri, Scarab-Warden",
        "species": "khepri",
        "canon": "NETJER",
        "flavor": "Dung-beetle who rolls the morning sun up from the underworld; the rebirth is in the rolling.",
        "moves": {
            "Rallying Roar": "Scarab's Summons",
            "Plate of Calm": "Carapace of Khepri",
        },
    },
    "rootsnake": {
        "name": "Uraeus-Root",
        "species": "uraeus_root",
        "canon": "NETJER",
        "flavor": "Cobra-root of the temple garden; the king's brow remembers what the soil first held.",
        "moves": {},
    },
    "thornpup": {
        "name": "Ammit Cub",
        "species": "ammit_cub",
        "canon": "NETJER",
        "flavor": "Soul-devourer's young; the jaws are small but the ledger is already long.",
        "moves": {"Bramblecoat": "Devourer's Coat"},
    },
    "sproutling": {
        "name": "Lotus of Nefertum",
        "species": "lotus_nefertum",
        "canon": "NETJER",
        "flavor": "Sacred lotus of the perfume-god; the bloom opens at dawn and the wound forgets itself.",
        "moves": {},
    },
    "arc_kit": {
        "name": "Set-Whelp",
        "species": "set_whelp",
        "canon": "NETJER",
        "flavor": "Storm-chaos god's young; the red-land wind learns its shape around him.",
        "moves": {},
    },
    "arc_lancer": {
        "name": "Set Initiate",
        "species": "set_initiate",
        "canon": "NETJER",
        "flavor": "Servant of the red-land lord; he carries the storm under the skin like a scar.",
        "moves": {},
    },
    "plasma_hound": {
        "name": "Set-Hound",
        "species": "set_hound",
        "canon": "NETJER",
        "flavor": "Jackal of the red desert; storm in the throat, sand in the paw, hunger in the eye.",
        "moves": {},
    },
    "galekit": {
        "name": "Shezmu-Whelp",
        "species": "shezmu_whelp",
        "canon": "NETJER",
        "flavor": "Young of the blood-pressing executioner-god; the cup that he learns to hold is not water.",
        "moves": {},
    },
    "wraithling": {
        "name": "Ushabti",
        "species": "ushabti",
        "canon": "NETJER",
        "flavor": "Tomb-servant figurine; called by name, he rises and labors in the field of reeds.",
        "moves": {},
    },
    "wraith_prince": {
        "name": "Wepwawet Herald",
        "species": "wepwawet_herald",
        "canon": "NETJER",
        "flavor": "Opener-of-Ways; where he falls the path opens, and the army follows the breach.",
        "moves": {},
    },
    "hollowpup": {
        "name": "Anubis Pup",
        "species": "anubis_pup",
        "canon": "NETJER",
        "flavor": "Jackal-child of the embalmer-god; the linen waits, the scale waits, the pup waits.",
        "moves": {},
    },
    "ghostfin": {
        "name": "Oxyrhynchus",
        "species": "oxyrhynchus",
        "canon": "NETJER",
        "flavor": "Sacred Nile-fish that ate the lost piece of Osiris; what it tasted, it remembers as venom.",
        "moves": {},
    },
    "ghoul_imp": {
        "name": "Servant of Ammit",
        "species": "ammit_servant",
        "canon": "NETJER",
        "flavor": "Lesser soul-eater; he gathers the crumbs the great devourer leaves on the scale.",
        "moves": {},
    },
    "cryptmoth": {
        "name": "Scarab-Moth",
        "species": "scarab_moth",
        "canon": "NETJER",
        "flavor": "Psychopomp moth of the necropolis; the wing-dust marks the path the soul forgets.",
        "moves": {},
    },
    "silentmoth": {
        "name": "Hypocephalus Moth",
        "species": "hypocephalus_moth",
        "canon": "NETJER",
        "flavor": "Amulet-moth of silent passage; she lays the disk beneath the head of the dead.",
        "moves": {},
    },
    "dread_imp": {
        "name": "Apep-Imp",
        "species": "apep_imp",
        "canon": "NETJER",
        "flavor": "Lesser chaos-spawn of the night-serpent; even his shadow makes the cobra recoil.",
        "moves": {"Cower Aura": "Chaos-Aura"},
    },
    "shadebishop": {
        "name": "Priest of Set",
        "species": "set_priest",
        "canon": "NETJER",
        "flavor": "He drinks the falling-of-allies as wine; the red-land god approves the cup.",
        "moves": {},
    },
    "shadepup": {
        "name": "Shade of Duat",
        "species": "duat_shade",
        "canon": "NETJER",
        "flavor": "Nameless walker of the underworld; what name he had was weighed and found wanting.",
        "moves": {},
    },
    "spectral_kit": {
        "name": "Serket-Kit",
        "species": "serket_kit",
        "canon": "NETJER",
        "flavor": "Scorpion-goddess's young; the tail is small still, but the venom is the venom of Serket.",
        "moves": {},
    },
    "spectral_owl": {
        "name": "Nocturnal Ibis",
        "species": "nocturnal_ibis",
        "canon": "NETJER",
        "flavor": "Thoth's night-bird; he reads the stars as letters and the wound as a verse.",
        "moves": {"Soul Glance": "Thoth's Glance"},
    },
    "miasma_imp": {
        "name": "Pestilence of Sekhmet",
        "species": "pestilence_sekhmet",
        "canon": "NETJER",
        "flavor": "Plague-imp of the lion-goddess; she releases what she releases, and the scribes write fast.",
        "moves": {},
    },

    # ===================== KAMI =====================
    "emberhawk": {
        "name": "Karura Fledgling",
        "species": "karura",
        "canon": "KAMI",
        "flavor": "Garuda-bird of the Buddhist-Shinto sky; the fledgling already eats the small serpent whole.",
        "moves": {},
    },
    "ember_raptor": {
        "name": "Karura Adept",
        "species": "karura_adept",
        "canon": "KAMI",
        "flavor": "Grown into the wind-fire; he hunts the dragon now, not the snake.",
        "moves": {},
    },
    "flickerimp": {
        "name": "Hinode-Oni Whelp",
        "species": "hinode_oni",
        "canon": "KAMI",
        "flavor": "Dawn-demon young; the first red light is its first appetite.",
        "moves": {},
    },
    "cindermote": {
        "name": "Hi-no-Kagutsuchi Spark",
        "species": "kagutsuchi_spark",
        "canon": "KAMI",
        "flavor": "Ember of the fire-kami who burned his mother to the underworld at his birth.",
        "moves": {},
    },
    "embershrew": {
        "name": "Kamaitachi",
        "species": "kamaitachi",
        "canon": "KAMI",
        "flavor": "Wind-sickle weasel; the cut comes before the feeling; the feeling never comes.",
        "moves": {},
    },
    "coalmunch": {
        "name": "Okuribi",
        "species": "okuribi",
        "canon": "KAMI",
        "flavor": "Sending-fire that follows travelers; bow once, and it goes home with the polite.",
        "moves": {},
    },
    "mistling": {
        "name": "Ayakashi-Drift",
        "species": "ayakashi_drift",
        "canon": "KAMI",
        "flavor": "Sea-mist yōkai over the night-water; nothing seen, only something passing.",
        "moves": {},
    },
    "seapup": {
        "name": "Ryūjin Whelp",
        "species": "ryujin_whelp",
        "canon": "KAMI",
        "flavor": "Dragon-king's young; his cradle is a tide-pool, his lullaby is a typhoon.",
        "moves": {},
    },
    "shellfin": {
        "name": "Kappa Scholar",
        "species": "kappa_scholar",
        "canon": "KAMI",
        "flavor": "River-imp of letters; he keeps the bowl of water on his head and the bowl of ink at his side.",
        "moves": {},
    },
    "shellguard": {
        "name": "Kappa Warden",
        "species": "kappa_warden",
        "canon": "KAMI",
        "flavor": "Elder of the river-imps; the cucumber is left, the boat is let pass, the shrine is tended.",
        "moves": {},
    },
    "brineling": {
        "name": "Namazu Fry",
        "species": "namazu_fry",
        "canon": "KAMI",
        "flavor": "Earthquake-catfish young; small turn, small tremor; the keystone-stone holds, for now.",
        "moves": {},
    },
    "brineprince": {
        "name": "Namazu Lord",
        "species": "namazu_lord",
        "canon": "KAMI",
        "flavor": "Catfish under the islands; when the keystone slips, the rooftiles remember.",
        "moves": {},
    },
    "mosshound": {
        "name": "Inugami Pup",
        "species": "inugami_pup",
        "canon": "KAMI",
        "flavor": "Dog-spirit of the mossed shrine; faithful to the family that fed it, faithful past death.",
        "moves": {},
    },
    "mosscat": {
        "name": "Maneki-Neko Kit",
        "species": "maneki_neko_kit",
        "canon": "KAMI",
        "flavor": "Beckoning-cat young; the small paw lifts, and the morning comes well to the household.",
        "moves": {},
    },
    "mossling": {
        "name": "Kodama Sapling",
        "species": "kodama",
        "canon": "KAMI",
        "flavor": "Tree-spirit's youngest form; the cedar-knock answers when none of the kin will speak.",
        "moves": {},
    },
    "root_warden": {
        "name": "Kodama Warden",
        "species": "kodama_warden",
        "canon": "KAMI",
        "flavor": "Grown tree-spirit; do not fell the trunk that does not answer the axe.",
        "moves": {},
    },
    "stonepup": {
        "name": "Komainu Pup",
        "species": "komainu_pup",
        "canon": "KAMI",
        "flavor": "Shrine lion-dog young; even the cub at the gate makes the bad spirit hesitate.",
        "moves": {},
    },
    "thornling": {
        "name": "Jorōgumo Thread",
        "species": "jorogumo_thread",
        "canon": "KAMI",
        "flavor": "First strand of the spider-spirit; pretty, fine, and waiting for the second strand.",
        "moves": {},
    },
    "thornserpent": {
        "name": "Jorōgumo Warden",
        "species": "jorogumo_warden",
        "canon": "KAMI",
        "flavor": "Grown spider-spirit; the parlor is set, the visitor is welcome, the visitor is not leaving.",
        "moves": {},
    },
    "zapling": {
        "name": "Raiju Whelp",
        "species": "raiju_whelp",
        "canon": "KAMI",
        "flavor": "Thunder-beast young; in the storm he sleeps in the navel of the careless sleeper.",
        "moves": {},
    },
    "zapdrake": {
        "name": "Raiju Initiate",
        "species": "raiju_initiate",
        "canon": "KAMI",
        "flavor": "Thunder-beast grown; the bolt is the body, the body is the bolt's choice of road.",
        "moves": {},
    },
    "boltkit": {
        "name": "Raijin-Kit",
        "species": "raijin_kit",
        "canon": "KAMI",
        "flavor": "Thunder-god's attendant-young; the small drum learns the cadence of the storm.",
        "moves": {},
    },
    "boltrunner": {
        "name": "Raijin Herald",
        "species": "raijin_herald",
        "canon": "KAMI",
        "flavor": "Thunder-god's messenger; he runs the road of clouds and arrives before his footfall.",
        "moves": {},
    },
    "stormpup": {
        "name": "Fūjin Pup",
        "species": "fujin_pup",
        "canon": "KAMI",
        "flavor": "Wind-god's young; the bag at his back is small, but the wind in it is the same wind.",
        "moves": {},
    },
    "shockling": {
        "name": "Rai-Mote",
        "species": "rai_mote",
        "canon": "KAMI",
        "flavor": "Thunder-spark; brief life, bright life, the cicada of the storm.",
        "moves": {},
    },
    "shock_runner": {
        "name": "Raijin Drumroller",
        "species": "raijin_drum",
        "canon": "KAMI",
        "flavor": "Thunder-god's drum-beater; the cadence is the thunder, the thunder is the cadence.",
        "moves": {},
    },
    "arcweasel": {
        "name": "Kamaitachi Jr.",
        "species": "kamaitachi_jr",
        "canon": "KAMI",
        "flavor": "Younger wind-sickle; he learns the cut from his elder, and the elder is a quick teacher.",
        "moves": {},
    },
    "arc_pup": {
        "name": "Raiju Cub",
        "species": "raiju_cub",
        "canon": "KAMI",
        "flavor": "Thunder-wolf juvenile; the play-bite already crackles.",
        "moves": {},
    },
    "arc_predator": {
        "name": "Raijū-Taishō",
        "species": "raiju_taisho",
        "canon": "KAMI",
        "flavor": "Thunder-beast commander; the pack moves where the storm leans, and the storm leans where he turns.",
        "moves": {
            "Bolt Hunger": "Thunder-Beast Hunger",
            "Cull Strike": "Taishō's Cull",
        },
    },
    "boltbat": {
        "name": "Raiju-Hatchling",
        "species": "raiju_hatchling",
        "canon": "KAMI",
        "flavor": "Newborn thunder-beast; the wings have not yet learned to fold, the bolt has.",
        "moves": {},
    },
    "spark_imp": {
        "name": "Oni-Spark",
        "species": "oni_spark",
        "canon": "KAMI",
        "flavor": "Lesser demon-spark from the iron club; small, but the bruise it leaves is purple-blue.",
        "moves": {},
    },
    "plasma_kit": {
        "name": "Raijin Acolyte",
        "species": "raijin_acolyte",
        "canon": "KAMI",
        "flavor": "Young Raijin-servant; the drumstick is borrowed, the cadence is true.",
        "moves": {},
    },
    "shadeling": {
        "name": "Shinigami Initiate",
        "species": "shinigami_init",
        "canon": "KAMI",
        "flavor": "Young death-spirit; the ledger is short, but the hand that writes it is patient.",
        "moves": {},
    },
    "duskmoth": {
        "name": "Mothra of Yomi",
        "species": "yomi_moth",
        "canon": "KAMI",
        "flavor": "Moth that flies between the lit world and the underworld; the wings carry the ash of both.",
        "moves": {},
    },
    "shade_prismatic": {
        "name": "Yōkai Chorus",
        "species": "yokai_chorus",
        "canon": "KAMI",
        "flavor": "Many spirits, one voice; the night-procession becomes a single agreed song.",
        "moves": {},
    },
    "shadeprism": {
        "name": "Yōkai Whisper",
        "species": "yokai_whisper",
        "canon": "KAMI",
        "flavor": "Many spirits, one murmur; you cannot hear it; you have already answered it.",
        "moves": {},
    },
    "dirgebat": {
        "name": "Onryō-Bat",
        "species": "onryo_bat",
        "canon": "KAMI",
        "flavor": "Vengeful-ghost in bat-form; she remembers the room, she remembers the door, she remembers the name.",
        "moves": {},
    },
    "flashfox": {
        "name": "Tenko-Kit",
        "species": "tenko_kit",
        "canon": "KAMI",
        "flavor": "Heaven-fox's young; her tail will be many in time, and her bolt will be one.",
        "moves": {},
    },
    "galelord": {
        "name": "Fūjin Herald",
        "species": "fujin_herald",
        "canon": "KAMI",
        "flavor": "Wind-god's envoy; he opens the bag a hand's-width and the army is fast.",
        "moves": {},
    },
    "tidemerger": {
        "name": "Mizu-no-Yōkai Jr.",
        "species": "mizu_yokai_jr",
        "canon": "KAMI",
        "flavor": "Young water-spirit of confluences; he learns where two rivers become a third name.",
        "moves": {},
    },
    "tide_synth": {
        "name": "Mizu-no-Yōkai Adept",
        "species": "mizu_yokai_adept",
        "canon": "KAMI",
        "flavor": "Grown confluence-spirit; the rivers meet at his palm and remember the meeting.",
        "moves": {},
    },

    # ===================== TEOTL =====================
    "rainbow_drake": {
        "name": "Quetzalcóatl, Plumed One",
        "species": "quetzalcoatl",
        "canon": "TEOTL",
        "flavor": "Plumed serpent of sky and earth; he gave the people maize and the calendar, then walked east.",
        "moves": {
            "Many-Hued Pulse": "Plumed Pulse",
            "Iridescent Ward": "Quetzal-Feather Ward",
        },
    },
    "sunscale_drake": {
        "name": "Quetzalcóatl Hatchling",
        "species": "quetzalcoatl_hatchling",
        "canon": "TEOTL",
        "flavor": "Plumed serpent's young; the down is already the color of the dawn-sky.",
        "moves": {},
    },
    "sunscale_serpent": {
        "name": "Quetzalcóatl Adept",
        "species": "quetzalcoatl_adept",
        "canon": "TEOTL",
        "flavor": "Grown plumed serpent; he learns the names of the four winds and answers each in turn.",
        "moves": {},
    },
    "blazewolf": {
        "name": "Xolotl, Dog-Star",
        "species": "xolotl",
        "canon": "TEOTL",
        "flavor": "Dog-headed twin of the plumed one; he guides the sun through the night-country and back.",
        "moves": {"Pack Roar": "Twin-of-the-Sun Roar"},
    },
    "ashling": {
        "name": "Xiuhcoatl Spark",
        "species": "xiuhcoatl_spark",
        "canon": "TEOTL",
        "flavor": "Ember of the turquoise fire-serpent; the sun eats thirteen hearts, the spark eats one.",
        "moves": {},
    },
    "blazefiend": {
        "name": "Xiuhcoatl Adept",
        "species": "xiuhcoatl_adept",
        "canon": "TEOTL",
        "flavor": "Initiate of the fire-serpent cult; he aims the venom-flame and the weakest is named first.",
        "moves": {},
    },
    "ignis_kit": {
        "name": "Xipe Totec Cub",
        "species": "xipe_cub",
        "canon": "TEOTL",
        "flavor": "Flayed-god's young; the skin he sheds becomes the spring he gives.",
        "moves": {},
    },
    "coalwhelp": {
        "name": "Obsidian Pup",
        "species": "obsidian_pup",
        "canon": "TEOTL",
        "flavor": "Jaguar-warrior's young; the obsidian club is his teething-stone.",
        "moves": {},
    },
    "coalbreaker": {
        "name": "Jaguar Warrior",
        "species": "jaguar_warrior",
        "canon": "TEOTL",
        "flavor": "Ocelotl initiate; the pelt is earned, the kill is recorded, the sun is fed.",
        "moves": {},
    },
    "soot_finch": {
        "name": "Tototl-Warrior",
        "species": "tototl_warrior",
        "canon": "TEOTL",
        "flavor": "Bird-warrior of the codex-fields; the war-cry is the song, the song is the cry.",
        "moves": {},
    },
    "magmaling": {
        "name": "Tlāhuiztli Whelp",
        "species": "tlahuiztli",
        "canon": "TEOTL",
        "flavor": "Solar-warrior's young; the feathered tunic is too large still — for now.",
        "moves": {},
    },
    "magma_warden": {
        "name": "Tlāhuiztli Commander",
        "species": "tlahuiztli_cmdr",
        "canon": "TEOTL",
        "flavor": "Elder solar-warrior; the tunic fits, the orders carry, the sun is fed on schedule.",
        "moves": {},
    },
    "flame_chimerlet": {
        "name": "Xochitonal Whelp",
        "species": "xochitonal",
        "canon": "TEOTL",
        "flavor": "Flower-fire spirit's young; the bloom and the spark are the same gesture, just younger.",
        "moves": {},
    },
    "flame_chimera_adept": {
        "name": "Xochitonal Adept",
        "species": "xochitonal_adept",
        "canon": "TEOTL",
        "flavor": "Grown flower-fire spirit; the petal opens, the spark answers the petal's invitation.",
        "moves": {},
    },
    "emberpup": {
        "name": "Ocelocoyotl Pup",
        "species": "ocelocoyotl_pup",
        "canon": "TEOTL",
        "flavor": "Jaguar-coyote hybrid pup; the bite is the jaguar's, the laugh is the coyote's.",
        "moves": {},
    },
    "abyss_warden": {
        "name": "Chalchiuhtlicue, Jade-Skirt",
        "species": "chalchiuhtlicue",
        "canon": "TEOTL",
        "flavor": "Lake-and-river goddess; her skirt of jade is the green water that drowns and the green water that gives.",
        "moves": {
            "Quietus": "Jade-Skirt's Quiet",
            "Ledger Closes": "Lake's Ledger Closes",
        },
    },
    "tidepup": {
        "name": "Ahuizotl Pup",
        "species": "ahuizotl_pup",
        "canon": "TEOTL",
        "flavor": "Lagoon-dog's young; the tail-hand is small, the snatch-from-the-bank is already practiced.",
        "moves": {},
    },
    "surfling": {
        "name": "Acihuatl Sprite",
        "species": "acihuatl",
        "canon": "TEOTL",
        "flavor": "Water-nymph of the Mexica lakes; she carries the gourd that does not empty.",
        "moves": {},
    },
    "mistchimera": {
        "name": "Tlaloc's Mist",
        "species": "tlaloc_mist",
        "canon": "TEOTL",
        "flavor": "Vaporous envoy of the rain-god; the mist is the message, the mist is the rain to come.",
        "moves": {},
    },
    "mistchimera_adept": {
        "name": "Tlaloc's Storm-Mist",
        "species": "tlaloc_storm_mist",
        "canon": "TEOTL",
        "flavor": "Grown rain-mist envoy; the cloud is heavy now and the field will know it by morning.",
        "moves": {},
    },
    "prism_chimera": {
        "name": "Coatlicue, Serpent-Skirt",
        "species": "coatlicue",
        "canon": "TEOTL",
        "flavor": "Earth-mother of the serpent-skirt; she gave birth to the sun and the moon, and to a war between them.",
        "moves": {
            "Many-Voiced Vow": "Serpent-Skirt's Vow",
            "Spectral Lash": "Obsidian-Tongue Lash",
        },
    },
    "prism_seedling": {
        "name": "Xochitl Seed",
        "species": "xochitl_seed",
        "canon": "TEOTL",
        "flavor": "Sacred flower-seed of the codex; planted in the right month, it answers the right god.",
        "moves": {},
    },
    "prism_grove": {
        "name": "Xochipilli Grove",
        "species": "xochipilli_grove",
        "canon": "TEOTL",
        "flavor": "Flower-prince's bloom; the grove sings without breath and the warrior remembers the field.",
        "moves": {},
    },
    "verdant_chimerlet": {
        "name": "Mayahuel Whelp",
        "species": "mayahuel",
        "canon": "TEOTL",
        "flavor": "Maguey-goddess's young; the leaf-shield is the gift, the sap-wine is the second gift.",
        "moves": {},
    },
    "verdant_chimera": {
        "name": "Mayahuel Adept",
        "species": "mayahuel_adept",
        "canon": "TEOTL",
        "flavor": "Grown maguey-priestess; the agave's four hundred breasts answer four hundred gods.",
        "moves": {},
    },
    "charge_chick": {
        "name": "Hummingbird of Huitzilopochtli",
        "species": "huitzil_chick",
        "canon": "TEOTL",
        "flavor": "Sacred warrior-hummingbird; the small beak drinks the small heart and asks for the next.",
        "moves": {},
    },
    "spectral_volt": {
        "name": "Teoyaomiqui Spark",
        "species": "teoyaomiqui",
        "canon": "TEOTL",
        "flavor": "Spark of the war-dead; he came home as a hummingbird and as this small bright thing.",
        "moves": {},
    },
    "spectral_charge": {
        "name": "Teoyaomiqui Adept",
        "species": "teoyaomiqui_adept",
        "canon": "TEOTL",
        "flavor": "Grown war-dead spirit; he carries the obsidian and the calendar to the next sun.",
        "moves": {},
    },
    "dashmouse": {
        "name": "Ehecatl Mouse",
        "species": "ehecatl_mouse",
        "canon": "TEOTL",
        "flavor": "Wind-god's scurrier; he runs ahead of the rain and the rain says he is welcome.",
        "moves": {"Spark Dash": "Wind-Foot Dash"},
    },
    "world_eater": {
        "name": "Tezcatlipoca, Smoking Mirror",
        "species": "tezcatlipoca",
        "canon": "TEOTL",
        "flavor": "Night-jaguar primordial; the mirror smokes and the world is here, and the world is here.",
        "moves": {
            "Many-Hued Roar": "Mirror's Roar",
            "Spectral Maw": "Night-Jaguar Maw",
            "World-Devouring": "Smoking-Mirror Devouring",
        },
    },
    "void_chimerlet": {
        "name": "Tzitzimitl Spawn",
        "species": "tzitzimitl",
        "canon": "TEOTL",
        "flavor": "Star-demon's young; in the eclipse-hour she opens her eyes for the first time.",
        "moves": {},
    },
    "void_chimera": {
        "name": "Tzitzimitl Adept",
        "species": "tzitzimitl_adept",
        "canon": "TEOTL",
        "flavor": "Grown star-demon; if the sun should fail, she comes down for the children at noon.",
        "moves": {},
    },
    "voidcrawler": {
        "name": "Xolotl-Shadow",
        "species": "xolotl_shadow",
        "canon": "TEOTL",
        "flavor": "Death-twin's shade; he is the dog at the heel of the soul, and the soul does not refuse him.",
        "moves": {"Seam Bite": "Twin-Shadow's Bite"},
    },
    "nullsprite": {
        "name": "Mictlan-Wisp",
        "species": "mictlan_wisp",
        "canon": "TEOTL",
        "flavor": "Wisp of the nine-layered underworld; she lights the fourth river and the fourth river only.",
        "moves": {},
    },

    # ===================== APOCRYPHA =====================
    "concord_phoenix": {
        "name": "The First Ancestor",
        "species": "first_ancestor",
        "canon": "APOCRYPHA",
        "flavor": "The eldest of the village dead; bless the field and the new-fallen step into the line.",
        "moves": {},
    },
    "aegis_lion": {
        "name": "Nemean Wanderer",
        "species": "nemean_wanderer",
        "canon": "APOCRYPHA",
        "flavor": "Lion of no temple; he keeps the crossroads, and the road keeps him, and that is enough.",
        "moves": {},
    },
    "loremaster_ape": {
        "name": "Sanzaru",
        "species": "sanzaru",
        "canon": "KAMI",
        "flavor": "See-no, hear-no, speak-no — the three become one, and the one teaches the troop.",
        "moves": {},
    },
    "mendicant_sphinx": {
        "name": "Crossroads Sphinx",
        "species": "crossroads_sphinx",
        "canon": "APOCRYPHA",
        "flavor": "Riddleless sphinx of the highway; he asks the price of bread and lets you pass.",
        "moves": {},
    },
    "rune_owl": {
        "name": "Soothsayer Owl",
        "species": "soothsayer_owl",
        "canon": "APOCRYPHA",
        "flavor": "Hedge-witch's familiar; she reads the barley-stalk and the barley-stalk reads her back.",
        "moves": {},
    },
    "stoneward": {
        "name": "Cairn-Warden",
        "species": "cairn_warden",
        "canon": "APOCRYPHA",
        "flavor": "Stone-stacker of the mountain path; add a stone, and you will come back down.",
        "moves": {},
    },
    "wrought_bear": {
        "name": "Iron-Tongued Bear",
        "species": "iron_bear",
        "canon": "APOCRYPHA",
        "flavor": "Bear-spirit of the parish; he speaks once a year and the village writes it down.",
        "moves": {},
    },
    "brass_mole": {
        "name": "Brass Mole",
        "species": "brass_mole",
        "canon": "APOCRYPHA",
        "flavor": "Earth-worker of the old folk; the brass is the color of the soil it has crossed.",
        "moves": {},
    },
    "cloth_sprite": {
        "name": "Brownie",
        "species": "brownie",
        "canon": "APOCRYPHA",
        "flavor": "Household helper; he patches the cloak in the night and asks no thanks but the milk.",
        "moves": {},
    },
    "grove_pup": {
        "name": "Grove Hob",
        "species": "grove_hob",
        "canon": "APOCRYPHA",
        "flavor": "Hedge-child between the rows; he trots between the wounded and is gone before the thanks.",
        "moves": {},
    },
    "mossback_ox": {
        "name": "Old Ox of the Parish",
        "species": "parish_ox",
        "canon": "APOCRYPHA",
        "flavor": "Unmoveable farm-guardian; the field is plowed where he stops and not before.",
        "moves": {},
    },
    "page_slime": {
        "name": "Marginalia",
        "species": "marginalia",
        "canon": "APOCRYPHA",
        "flavor": "Book-margin spirit; he writes a small hand in the white space and the wound forgets the page.",
        "moves": {},
    },
    "pebbler": {
        "name": "Dolmen Spirit",
        "species": "dolmen_spirit",
        "canon": "APOCRYPHA",
        "flavor": "Stone-cairn folk; older than the parish, older than the parish's saint.",
        "moves": {},
    },
    "quill_cat": {
        "name": "Thistle Cat",
        "species": "thistle_cat",
        "canon": "APOCRYPHA",
        "flavor": "Hedge-cat of the thorn-rows; he hunts what the hedge will not hunt itself.",
        "moves": {},
    },
    "runic_whelp": {
        "name": "Hedge-Scribe",
        "species": "hedge_scribe",
        "canon": "APOCRYPHA",
        "flavor": "Half-chant household spirit; he scratches a charm on the lintel and the hearth holds.",
        "moves": {},
    },
    "coralcub": {
        "name": "Jenny Greenteeth Pup",
        "species": "jenny_pup",
        "canon": "APOCRYPHA",
        "flavor": "Marsh-hag's juvenile; mind the ditch at twilight, mind the green skin under the duckweed.",
        "moves": {},
    },
    "boulder_mole": {
        "name": "Hodag",
        "species": "hodag",
        "canon": "APOCRYPHA",
        "flavor": "American forest-folk beast; lumpy-bristled and stand-your-ground; the stick rebounds.",
        "moves": {},
    },
    "sparkling": {
        "name": "Will-o'-Wisp",
        "species": "wisp",
        "canon": "APOCRYPHA",
        "flavor": "Swamp-light folk-spirit; follow it home and you will not arrive at the home you meant.",
        "moves": {},
    },
}

# --- Distribution sanity check (per-Canon counts) ---------------------------
# Targets (per audit §6 reconciliation, after Santiago Phoenix directive):
#   OLYMPIAN 38 / AESIR 37 / NETJER 32 / KAMI 37 / TEOTL 32 / APOCRYPHA 18
# Final actual counts in this file (verified via `python3 mapping.py`):
#   OLYMPIAN  38
#   AESIR     38   (+1: cinderhound + geodeling absorbed per §2 reallocation, voidling new)
#   NETJER    30   (−2: solar_phoenix moved Olympian [Helios]; ghostfin/abyss_minnow shifts
#                       were audit-mandated within-Netjer renames; dread_imp→Apep-Imp kept
#                       Netjer; count lands 2 short)
#   KAMI      43   (+6: mossbear, loremaster_ape [Sanzaru], flashfox, boltbat [Raiju-Hatchling],
#                       mistling [Ayakashi-Drift], mosscat [Maneki-Neko]; all audit-mandated)
#   TEOTL     34   (+2: soot_finch, emberpup swaps stayed Teotl per audit; verdant pair
#                       stayed Teotl as Mayahuel; mistchimera_adept stayed WATER-Teotl)
#   APOCRYPHA 17   (−1: loremaster_ape to Kami Sanzaru; concord_phoenix kept as
#                       The First Ancestor; boulder_mole [Hodag] kept Apocrypha)
# Total: 200 ✓
#
# Drift notes (acknowledged, not bugs):
#   - Distribution per the audit was a planning aid; audit §2/§3 overrides were specified as
#     AUTHORITATIVE even when they skew the distribution. This file honors the overrides.
#   - NETJER under by 2 is the cleanest outcome: Helios is a better mechanical fit for
#     solar_phoenix than Bennu (opening AOE = dawn-chariot; heal-on-death = sunset-bleed)
#     and frees Bennu for V2 per Santiago directive.
#   - KAMI at 43 is the cleanest outcome: every KAMI card in this file is either the
#     audit-prescribed rewrite or a preserved clean-match from §4; pulling cards back out
#     would contradict the audit's primary purpose.
#   - APOCRYPHA at 17 is 1 below the audit's 18 floor — acceptable per audit §6 option 2
#     ("accept revised target and revise canon_mapping.md §2 to reflect actual ship
#     counts"). concord_phoenix stays Apocrypha (The First Ancestor replaces The First
#     Phoenix); no phoenix-family cards landed back here.
#
# Improvisations / oddities flagged:
#   - tidemerger / tide_synth: no attested Mizu-no-Yōkai evolution-pair in primary sources;
#     coined "Mizu-no-Yōkai Jr." / "Mizu-no-Yōkai Adept" per canon_mapping §10 problem-spot
#     fix to keep the WATER/SYNCRETIC chain inside KAMI (both have no moves to rename).
#   - prismbolt: canon_mapping §10 projected "Iris-Mote → Iris, Rainbow-Courier" — applied
#     verbatim (Iris-Mote, OLYMPIAN VOLT common, no moves).
#   - Both magma_tyrant and ashen_phoenix carry "Prometheus" identities per the Santiago
#     directive's explicit allowance; mythologically continuous (Fire-Thief bound →
#     Prometheus-Unbound the suffering-gift-giver). Not a bug.
#   - Species stem "skogsra" appears on both barkpup (Pup) and barkguard (Warden) — this is
#     the intended AESIR evolution-pair per canon_mapping §5.
#   - No emojis anywhere; all flavors ≤110 chars (verified).

if __name__ == "__main__":
    # Self-check: assert all keys are unique and count per-canon.
    from collections import Counter
    canons = Counter(v["canon"] for v in MAPPING.values())
    print(f"Total entries: {len(MAPPING)}")
    for canon in ("OLYMPIAN", "AESIR", "NETJER", "KAMI", "TEOTL", "APOCRYPHA"):
        print(f"  {canon:10s} {canons.get(canon, 0)}")
